// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ML.WorkShop.BLL.UnitTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class 員工資料管理Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "員工資料管理.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "員工資料管理", "\t員工資料維護系統", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "員工資料管理")))
            {
                global::ML.WorkShop.BLL.UnitTest.員工資料管理Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("新增一筆員工資料")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "員工資料管理")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void 新增一筆員工資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("新增一筆員工資料", new string[] {
                        "mytag"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CompanyId",
                        "WorkId",
                        "RoleName",
                        "Email",
                        "Name",
                        "Age",
                        "Password"});
            table1.AddRow(new string[] {
                        "1",
                        "DDMC",
                        "10608",
                        "Member",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "1234"});
#line 6
 testRunner.Given("前端應傳來以下MemberViewModel資料", ((string)(null)), table1, "Given ");
#line 10
 testRunner.When("調用MemberWorkflow.Insert", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "WorkId",
                        "CompanyId",
                        "Email",
                        "Name",
                        "Age",
                        "CreateUserId",
                        "CreateDateTime"});
            table2.AddRow(new string[] {
                        "1",
                        "10608",
                        "0",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 12
 testRunner.Then("預期資料庫的Member資料表應有以下資料", ((string)(null)), table2, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime"});
            table3.AddRow(new string[] {
                        "1",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 16
 testRunner.And("預期資料庫的Identity資料表應有以下資料", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Email",
                        "Name",
                        "Age",
                        "WorkId",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime"});
            table4.AddRow(new string[] {
                        "1",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "10608",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 20
 testRunner.And("預期資料庫的MemberLog資料表應有以下資料", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Member",
                        "CreateDateTime",
                        "CreateUserId"});
            table5.AddRow(new string[] {
                        "1",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
#line 24
 testRunner.And("預期資料庫的Role資料表應有以下資料", ((string)(null)), table5, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("編輯一筆員工資料")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "員工資料管理")]
        public virtual void 編輯一筆員工資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("編輯一筆員工資料", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "WorkId",
                        "CompanyId",
                        "Email",
                        "Name",
                        "Age",
                        "CreateUserId",
                        "CreateDateTime"});
            table6.AddRow(new string[] {
                        "1",
                        "10608",
                        "0",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 29
 testRunner.Given("資料庫的Member資料表已經存在以下資料", ((string)(null)), table6, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime"});
            table7.AddRow(new string[] {
                        "1",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 33
 testRunner.And("資料庫的Identity資料表已經存在以下資料", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Member",
                        "CreateDateTime",
                        "CreateUserId"});
            table8.AddRow(new string[] {
                        "1",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
#line 37
 testRunner.And("資料庫的Role資料表已經存在以下資料", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Email",
                        "Name",
                        "Age",
                        "WorkId",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime"});
            table9.AddRow(new string[] {
                        "1",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "10608",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 41
 testRunner.And("資料庫的MemberLog資料表已經存在以下資料", ((string)(null)), table9, "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CompanyId",
                        "WorkId",
                        "RoleName",
                        "Email",
                        "Name",
                        "Age",
                        "Password"});
            table10.AddRow(new string[] {
                        "1",
                        "DDMC",
                        "10608",
                        "Member",
                        "Yami@aa.bb",
                        "Yami",
                        "25",
                        "54321"});
#line 45
 testRunner.And("前端應傳來以下MemberViewModel資料", ((string)(null)), table10, "And ");
#line 49
 testRunner.When("調用MemberWorkflow.Update", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "WorkId",
                        "CompanyId",
                        "Email",
                        "Name",
                        "Age",
                        "CreateUserId",
                        "CreateDateTime",
                        "LastModifyUserId",
                        "LastModifyDateTime"});
            table11.AddRow(new string[] {
                        "1",
                        "10608",
                        "0",
                        "Yami@aa.bb",
                        "Yami",
                        "25",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 51
 testRunner.Then("預期資料庫的Member資料表應有以下資料", ((string)(null)), table11, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime",
                        "LastModifyUserId",
                        "LastModifyDateTime"});
            table12.AddRow(new string[] {
                        "1",
                        "54321",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 55
 testRunner.And("預期資料庫的Identity資料表應有以下資料", ((string)(null)), table12, "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Email",
                        "Name",
                        "Age",
                        "WorkId",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime",
                        "LastModifyUserId",
                        "LastModifyDateTime"});
            table13.AddRow(new string[] {
                        "1",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "10608",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "",
                        ""});
            table13.AddRow(new string[] {
                        "1",
                        "Yami@aa.bb",
                        "Yami",
                        "25",
                        "10608",
                        "54321",
                        "",
                        "",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 59
 testRunner.And("預期資料庫的MemberLog資料表應有以下資料", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Member",
                        "CreateDateTime",
                        "CreateUserId",
                        "LastModifyUserId",
                        "LastModifyDateTime"});
            table14.AddRow(new string[] {
                        "1",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 64
 testRunner.And("預期資料庫的Role資料表應有以下資料", ((string)(null)), table14, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("刪除一筆員工資料")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "員工資料管理")]
        public virtual void 刪除一筆員工資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("刪除一筆員工資料", ((string[])(null)));
#line 68
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "WorkId",
                        "CompanyId",
                        "Email",
                        "Name",
                        "Age",
                        "CreateUserId",
                        "CreateDateTime"});
            table15.AddRow(new string[] {
                        "1",
                        "10608",
                        "0",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 69
 testRunner.Given("資料庫的Member資料表已經存在以下資料", ((string)(null)), table15, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime"});
            table16.AddRow(new string[] {
                        "1",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 73
 testRunner.And("資料庫的Identity資料表已經存在以下資料", ((string)(null)), table16, "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Member",
                        "CreateDateTime",
                        "CreateUserId"});
            table17.AddRow(new string[] {
                        "1",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
#line 77
 testRunner.And("資料庫的Role資料表已經存在以下資料", ((string)(null)), table17, "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Email",
                        "Name",
                        "Age",
                        "WorkId",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime"});
            table18.AddRow(new string[] {
                        "1",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "10608",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 81
 testRunner.And("資料庫的MemberLog資料表已經存在以下資料", ((string)(null)), table18, "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CompanyId",
                        "WorkId",
                        "RoleName",
                        "Email",
                        "Name",
                        "Age",
                        "Password"});
            table19.AddRow(new string[] {
                        "1",
                        "DDMC",
                        "10608",
                        "Member",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "1234"});
#line 85
 testRunner.And("前端應傳來以下MemberViewModel資料", ((string)(null)), table19, "And ");
#line 89
 testRunner.When("調用MemberWorkflow.Delete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "WorkId",
                        "CompanyId",
                        "Email",
                        "Name",
                        "Age",
                        "CreateUserId",
                        "CreateDateTime",
                        "LastModifyUserId",
                        "LastModifyDateTime"});
#line 91
 testRunner.Then("預期資料庫的Member資料表應有以下資料", ((string)(null)), table20, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime",
                        "LastModifyUserId",
                        "LastModifyDateTime"});
#line 95
 testRunner.And("預期資料庫的Identity資料表應有以下資料", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Member",
                        "CreateDateTime",
                        "CreateUserId",
                        "LastModifyUserId",
                        "LastModifyDateTime"});
#line 98
 testRunner.And("預期資料庫的Role資料表應有以下資料", ((string)(null)), table22, "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Email",
                        "Name",
                        "Age",
                        "WorkId",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime",
                        "LastModifyUserId",
                        "LastModifyDateTime",
                        "DeleteUserId",
                        "DeleteDateTime"});
            table23.AddRow(new string[] {
                        "1",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "10608",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "",
                        "",
                        "",
                        ""});
            table23.AddRow(new string[] {
                        "1",
                        "yao@aa.bb",
                        "yao",
                        "18",
                        "10608",
                        "1234",
                        "",
                        "",
                        "",
                        "",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 101
 testRunner.And("預期資料庫的MemberLog資料表應有以下資料", ((string)(null)), table23, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("顯示員工資料表")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "員工資料管理")]
        public virtual void 顯示員工資料表()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("顯示員工資料表", ((string[])(null)));
#line 106
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "WorkId",
                        "CompanyId",
                        "Email",
                        "Name",
                        "Age",
                        "CreateUserId",
                        "CreateDateTime"});
            table24.AddRow(new string[] {
                        "1",
                        "10608",
                        "0",
                        "yao1@aa.bb",
                        "yao1",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table24.AddRow(new string[] {
                        "2",
                        "10609",
                        "0",
                        "yao2@aa.bb",
                        "yao2",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table24.AddRow(new string[] {
                        "3",
                        "10610",
                        "0",
                        "yao3@aa.bb",
                        "yao3",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table24.AddRow(new string[] {
                        "4",
                        "10611",
                        "0",
                        "yao4@aa.bb",
                        "yao4",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table24.AddRow(new string[] {
                        "5",
                        "10612",
                        "0",
                        "yao5@aa.bb",
                        "yao5",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table24.AddRow(new string[] {
                        "6",
                        "10613",
                        "0",
                        "yao6@aa.bb",
                        "yao6",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 107
 testRunner.Given("資料庫的Member資料表已經存在以下資料", ((string)(null)), table24, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime"});
            table25.AddRow(new string[] {
                        "1",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table25.AddRow(new string[] {
                        "2",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table25.AddRow(new string[] {
                        "3",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table25.AddRow(new string[] {
                        "4",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table25.AddRow(new string[] {
                        "5",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table25.AddRow(new string[] {
                        "6",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 116
 testRunner.And("資料庫的Identity資料表已經存在以下資料", ((string)(null)), table25, "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Administrator",
                        "Member",
                        "Lock",
                        "CreateDateTime",
                        "CreateUserId"});
            table26.AddRow(new string[] {
                        "1",
                        "true",
                        "false",
                        "false",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table26.AddRow(new string[] {
                        "2",
                        "false",
                        "true",
                        "false",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table26.AddRow(new string[] {
                        "3",
                        "false",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table26.AddRow(new string[] {
                        "4",
                        "false",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table26.AddRow(new string[] {
                        "5",
                        "true",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table26.AddRow(new string[] {
                        "6",
                        "false",
                        "true",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
#line 125
 testRunner.And("資料庫的Role資料表已經存在以下資料", ((string)(null)), table26, "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Member_Id",
                        "LoginDateTime",
                        "LastModifyPasswordDate"});
            table27.AddRow(new string[] {
                        "1",
                        "1",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table27.AddRow(new string[] {
                        "2",
                        "2",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table27.AddRow(new string[] {
                        "3",
                        "3",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table27.AddRow(new string[] {
                        "4",
                        "4",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table27.AddRow(new string[] {
                        "5",
                        "5",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table27.AddRow(new string[] {
                        "6",
                        "6",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
#line 134
 testRunner.And("資料庫的MemberActivity資料表已經存在以下資料", ((string)(null)), table27, "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Age",
                        "WorkId",
                        "ComapnyId"});
#line 142
 testRunner.And("前端應傳來以下MemberFilterModel資料", ((string)(null)), table28, "And ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "PageSize",
                        "PageIndex"});
            table29.AddRow(new string[] {
                        "10",
                        "0"});
#line 145
 testRunner.And("前端應傳來以下GridState資料", ((string)(null)), table29, "And ");
#line 148
 testRunner.When("調用MemberWorkflow.GetMembers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CompanyName",
                        "WorkId",
                        "Name",
                        "Email",
                        "Admin",
                        "Member",
                        "Lock",
                        "LastLoginDateTime",
                        "LastModifyPasswordDate"});
            table30.AddRow(new string[] {
                        "1",
                        "鼎鼎企業管理股份有限公司",
                        "10608",
                        "yao1",
                        "yao1@aa.bb",
                        "true",
                        "false",
                        "false",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table30.AddRow(new string[] {
                        "2",
                        "鼎鼎企業管理股份有限公司",
                        "10609",
                        "yao2",
                        "yao2@aa.bb",
                        "false",
                        "true",
                        "false",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table30.AddRow(new string[] {
                        "3",
                        "鼎鼎企業管理股份有限公司",
                        "10610",
                        "yao3",
                        "yao3@aa.bb",
                        "false",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table30.AddRow(new string[] {
                        "4",
                        "鼎鼎企業管理股份有限公司",
                        "10611",
                        "yao4",
                        "yao4@aa.bb",
                        "false",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table30.AddRow(new string[] {
                        "5",
                        "鼎鼎企業管理股份有限公司",
                        "10612",
                        "yao5",
                        "yao5@aa.bb",
                        "true",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table30.AddRow(new string[] {
                        "6",
                        "鼎鼎企業管理股份有限公司",
                        "10613",
                        "yao6",
                        "yao6@aa.bb",
                        "false",
                        "true",
                        "true",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
#line 150
 testRunner.Then("預期查詢得到以下MemberListViewModel資料", ((string)(null)), table30, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("查詢特定員工資料")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "員工資料管理")]
        public virtual void 查詢特定員工資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("查詢特定員工資料", ((string[])(null)));
#line 159
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "WorkId",
                        "CompanyId",
                        "Email",
                        "Name",
                        "Age",
                        "CreateUserId",
                        "CreateDateTime"});
            table31.AddRow(new string[] {
                        "1",
                        "10608",
                        "0",
                        "yao1@aa.bb",
                        "yao1",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table31.AddRow(new string[] {
                        "2",
                        "10609",
                        "0",
                        "yao2@aa.bb",
                        "yao2",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table31.AddRow(new string[] {
                        "3",
                        "10610",
                        "0",
                        "yao3@aa.bb",
                        "yao3",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table31.AddRow(new string[] {
                        "4",
                        "10611",
                        "0",
                        "yao4@aa.bb",
                        "yao4",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table31.AddRow(new string[] {
                        "5",
                        "10612",
                        "0",
                        "yao5@aa.bb",
                        "yao5",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table31.AddRow(new string[] {
                        "6",
                        "10613",
                        "0",
                        "yao6@aa.bb",
                        "yao6",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 160
 testRunner.Given("資料庫的Member資料表已經存在以下資料", ((string)(null)), table31, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime"});
            table32.AddRow(new string[] {
                        "1",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table32.AddRow(new string[] {
                        "2",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table32.AddRow(new string[] {
                        "3",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table32.AddRow(new string[] {
                        "4",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table32.AddRow(new string[] {
                        "5",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table32.AddRow(new string[] {
                        "6",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 169
 testRunner.And("資料庫的Identity資料表已經存在以下資料", ((string)(null)), table32, "And ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Administrator",
                        "Member",
                        "Lock",
                        "CreateDateTime",
                        "CreateUserId"});
            table33.AddRow(new string[] {
                        "1",
                        "true",
                        "false",
                        "false",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table33.AddRow(new string[] {
                        "2",
                        "false",
                        "true",
                        "false",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table33.AddRow(new string[] {
                        "3",
                        "false",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table33.AddRow(new string[] {
                        "4",
                        "false",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table33.AddRow(new string[] {
                        "5",
                        "true",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
            table33.AddRow(new string[] {
                        "6",
                        "false",
                        "true",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER"});
#line 178
 testRunner.And("資料庫的Role資料表已經存在以下資料", ((string)(null)), table33, "And ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Member_Id",
                        "LoginDateTime",
                        "LastModifyPasswordDate"});
            table34.AddRow(new string[] {
                        "1",
                        "1",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table34.AddRow(new string[] {
                        "2",
                        "2",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table34.AddRow(new string[] {
                        "3",
                        "3",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table34.AddRow(new string[] {
                        "4",
                        "4",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table34.AddRow(new string[] {
                        "5",
                        "5",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table34.AddRow(new string[] {
                        "6",
                        "6",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
#line 187
 testRunner.And("資料庫的MemberActivity資料表已經存在以下資料", ((string)(null)), table34, "And ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Age",
                        "WorkId",
                        "ComapnyName",
                        "Admin",
                        "Member",
                        "Lock"});
            table35.AddRow(new string[] {
                        "yao1@aa.bb",
                        "yao1",
                        "18",
                        "10608",
                        "鼎鼎",
                        "true",
                        "false",
                        "false"});
#line 195
 testRunner.And("前端應傳來以下MemberFilterModel資料", ((string)(null)), table35, "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "PageSize",
                        "PageIndex"});
            table36.AddRow(new string[] {
                        "10",
                        "0"});
#line 198
 testRunner.And("前端應傳來以下GridState資料", ((string)(null)), table36, "And ");
#line 201
 testRunner.When("調用MemberWorkflow.GetMembers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CompanyName",
                        "WorkId",
                        "Name",
                        "Email",
                        "Admin",
                        "Member",
                        "Lock",
                        "LastLoginDateTime",
                        "LastModifyPasswordDate"});
            table37.AddRow(new string[] {
                        "1",
                        "鼎鼎企業管理股份有限公司",
                        "10608",
                        "yao1",
                        "yao1@aa.bb",
                        "true",
                        "false",
                        "false",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
#line 203
 testRunner.Then("預期查詢得到以下MemberListViewModel資料", ((string)(null)), table37, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("查詢某員工詳細資料")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "員工資料管理")]
        public virtual void 查詢某員工詳細資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("查詢某員工詳細資料", ((string[])(null)));
#line 207
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "WorkId",
                        "CompanyId",
                        "Email",
                        "Name",
                        "Age",
                        "CreateUserId",
                        "CreateDateTime",
                        "LastModifyUserId",
                        "LastLoginDateTime"});
            table38.AddRow(new string[] {
                        "1",
                        "10608",
                        "0",
                        "yao1@aa.bb",
                        "yao1",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table38.AddRow(new string[] {
                        "2",
                        "10609",
                        "0",
                        "yao2@aa.bb",
                        "yao2",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table38.AddRow(new string[] {
                        "3",
                        "10610",
                        "0",
                        "yao3@aa.bb",
                        "yao3",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table38.AddRow(new string[] {
                        "4",
                        "10611",
                        "0",
                        "yao4@aa.bb",
                        "yao4",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table38.AddRow(new string[] {
                        "5",
                        "10612",
                        "0",
                        "yao5@aa.bb",
                        "yao5",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table38.AddRow(new string[] {
                        "6",
                        "10613",
                        "0",
                        "yao6@aa.bb",
                        "yao6",
                        "18",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 208
 testRunner.Given("資料庫的Member資料表已經存在以下資料", ((string)(null)), table38, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Member_Id",
                        "Password",
                        "CreateUserId",
                        "CreateDateTime",
                        "LastModifyUserId",
                        "LastLoginDateTime"});
            table39.AddRow(new string[] {
                        "1",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table39.AddRow(new string[] {
                        "2",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table39.AddRow(new string[] {
                        "3",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table39.AddRow(new string[] {
                        "4",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table39.AddRow(new string[] {
                        "5",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table39.AddRow(new string[] {
                        "6",
                        "1234",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 217
 testRunner.And("資料庫的Identity資料表已經存在以下資料", ((string)(null)), table39, "And ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Administrator",
                        "Member",
                        "Lock",
                        "CreateDateTime",
                        "CreateUserId",
                        "LastModifyUserId",
                        "LastLoginDateTime"});
            table40.AddRow(new string[] {
                        "1",
                        "true",
                        "false",
                        "false",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table40.AddRow(new string[] {
                        "2",
                        "false",
                        "true",
                        "false",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table40.AddRow(new string[] {
                        "3",
                        "false",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table40.AddRow(new string[] {
                        "4",
                        "false",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table40.AddRow(new string[] {
                        "5",
                        "true",
                        "false",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
            table40.AddRow(new string[] {
                        "6",
                        "false",
                        "true",
                        "true",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "TEST_USER",
                        "1900-01-01 00:00:00"});
#line 226
 testRunner.And("資料庫的Role資料表已經存在以下資料", ((string)(null)), table40, "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Member_Id",
                        "LoginDateTime",
                        "LastModifyPasswordDate"});
            table41.AddRow(new string[] {
                        "1",
                        "1",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table41.AddRow(new string[] {
                        "2",
                        "2",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table41.AddRow(new string[] {
                        "3",
                        "3",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table41.AddRow(new string[] {
                        "4",
                        "4",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table41.AddRow(new string[] {
                        "5",
                        "5",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
            table41.AddRow(new string[] {
                        "6",
                        "6",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
#line 235
 testRunner.And("資料庫的MemberActivity資料表已經存在以下資料", ((string)(null)), table41, "And ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table42.AddRow(new string[] {
                        "1"});
#line 244
 testRunner.And("前端應傳來以下MemberFilterModel資料", ((string)(null)), table42, "And ");
#line 248
 testRunner.When("調用MemberWorkflow.GetMemberDetail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CompanyName",
                        "Age",
                        "Password",
                        "WorkId",
                        "Name",
                        "Email",
                        "Admin",
                        "Member",
                        "Lock",
                        "CreateDateTime",
                        "CreateUserId",
                        "LastModifyUserId",
                        "LastLoginDateTime",
                        "LastLoginDateTime",
                        "LastModifyPasswordDate"});
            table43.AddRow(new string[] {
                        "1",
                        "鼎鼎企業管理股份有限公司",
                        "18",
                        "1234",
                        "10608",
                        "yao1",
                        "yao1@aa.bb",
                        "true",
                        "false",
                        "false",
                        "1900-01-01 00:00:00",
                        "TEST_USER",
                        "TEST_USER",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00",
                        "1900-01-01 00:00:00"});
#line 250
 testRunner.Then("預期查詢得到以下MemberDetailViewModel資料", ((string)(null)), table43, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion


